# Your Wi-Fi SSID and password
wifi_ssid: "wifi_ssid_goes_here"
wifi_password: "wifi_password_goes_here"

wifi_ap_password: "wifi_ap_password"

api_encryption_key: "api_encryption_key"
ota_password: "ota_password"

